AdvCBV/AdvCBV/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view() ),
    url(r'^basic_app/', include('basic_app.urls', namespace='basic_app')),
]

AdvCBV/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^$', views.SchoolListView.as_view(), name='list'),   # We assign a name here for the url template tag
    url(r'^rosters/$', views.RosterListView.as_view(), name='rosters'),
    url(r'^(?P<pk>\d+)/$', views.SchoolDetailView.as_view(), name='detail'),
    url(r'^create/$', views.SchoolCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name='delete'),
]

"""
pk is primary key

"""

AdvCBV/basic_app/models.py
from django.db import models
from django.core.urlresolvers import reverse
import datetime

# Create your models here.
class School(models.Model):
    SIXTY = '69ers'
    SPARTANS = 'Spartans'
    DIPS = 'Double Dips'
    BUSTS = 'Busts'
    BROWNS = 'Browns'
    GOFFS = 'Goffs'
    KAKAPOS = 'Kakpos'
    LUSTS = 'Lusts'

    TEAMS = (
    (SIXTY, '69ers'),
    (SPARTANS, 'Spartans'),
    (DIPS, 'Double Dips'),
    (BUSTS, 'Busts'),
    (BROWNS, 'Browns'),
    (GOFFS, 'Goffs'),
    (KAKAPOS, 'Kakpos'),
    (LUSTS, 'Lusts'),
    )
    team = models.CharField(max_length=256, choices=TEAMS)
    player = models.CharField(max_length=256)
    added_time = models.DateTimeField(default=datetime.datetime.now)

    TAXI = 'Taxi'
    IR = 'IR'
    ROSTER_CHOICES = (
        (TAXI, 'Taxi'),
        (IR, 'IR'),
    )
    roster = models.CharField(
        max_length=4,
        choices=ROSTER_CHOICES,
        default=TAXI,
    )

    IN = 'In'
    OUT = 'Out'
    CHANGE_CHOICES = (
        (IN, 'In'),
        (OUT, 'Out'),
    )
    change = models.CharField(
        max_length=4,
        choices=CHANGE_CHOICES,
        default=IN,
    )

    class Meta:
        ordering = ['added_time']

    def __str__(self):
        return self.player

    def get_absolute_url(self):
        return reverse("basic_app:detail", kwargs={'pk': self.pk})

AdvCBV/basic_app/views.py
from django.shortcuts import render
from . import models
from django.http import HttpResponse
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (View,TemplateView,ListView,DetailView,
                                CreateView,DeleteView,UpdateView)
import datetime

# Remeber this TemplateView is what our class will inherit from, not a parameter of a function
# If we use app subfolders in the template dir we would need to include that in the path here

class IndexView(TemplateView):
    template_name = 'index.html'


class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School
    # will generate "modelname_list" itself (all in lower case ).
    #  To avoid confusion later on we can define this ourselves

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('team', 'player', 'added_time', 'roster', 'change')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('team', 'player', 'added_time', 'roster', 'change')
    model = models.School
    success_url = reverse_lazy("basic_app:list")
    
    def get_initial(self):
        return { 'added_time': datetime.datetime.now}

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")


class RosterListView(ListView):
    context_object_name = 'rosters'
    model = models.School
    template_name = 'basic_app/roster_list.html'

    # def filter_user(self, team):
    #     return super(RosterListView, self).get_query_set().filter(team=team)

    # def get_queryset(self):
        # return School.object.order_by('-pub_date')[:5]

AdvCBV/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Transactions</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:create' %}">Add/Remove Player</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:rosters' %}">Rosters</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>

        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>
</html>

AdvCBV/basic_app/templates/basic_app/roster_list.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

<h1>Rosters</h1>

<div class="container">
{% with '69ers Spartans DoubleDips Busts Browns Goffs Kakpos Lusts' as list %}
  {% for i in list.split %}

        {% if forloop.first %}<div class="row">{% endif %}

          <div class="col-xs-3">
            <h3>{{i}}</h3>
            {% for school in rosters %}

              {# Add in taxi players #}
              {% if school.team == i and school.roster == 'Taxi' and school.change == 'In' %}
                <p><em>{{ school.roster }}</em> <a href="../{{school.id}}/">{{ school.player }}</a></p>
              {% endif %}

              {# Add in IR players #}
              {% if school.team == i and school.roster == 'IR' and school.change == 'In' %}
                <p><em>{{ school.roster }}</em> <a href="../{{school.id}}/">{{ school.player }}</a></p>
              {% endif %}

            {% endfor %}
          </div>
        {% if forloop.counter|divisibleby:4 %}</div><div class="row">{% endif %}
        {% if forloop.last %}</div>{% endif %}
  {% endfor %}
{% endwith %}
</div>



{% endblock %}

AdvCBV/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
  <h1>Are you sure you want to delete transaction for {{school.player}}?</h1>

  <form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>

  </form>

{% endblock %}

AdvCBV/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Transaction detail page</h1>
    <p>Team: {{school_detail.team}}</p>
    <p>Player: {{school_detail.player}}</p>
    <p>Changed time: {{school_detail.added_time}}</p>
    <p>Roster to/from: {{school_detail.roster}}</p>
    <p>Status: {{school_detail.change}}</p>

</div>

<div class="container">
  <p><a class = "btn btn-success" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a>
    <a class = "btn btn-danger" href="{% url 'basic_app:delete' pk=school_detail.pk %}">Delete</a>
    <a class = "btn btn-default" href="{% url 'basic_app:list' %}">Cancel</a>
  </p>
</div>

{% endblock %}

AdvCBV/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

  <h1>
    {% if not form.instance.pk %}
    Record transaction
    {% else %}
    Update transaction
    {% endif %}
  </h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Submit">
  </form>

{% endblock %}

AdvCBV/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

<h1>Transaction List </h1>

<div class="jumbotron">
  <h2>How to use:</h2>

  <ul>
    <li>To add a player to Taxi or IR squad:</li>
      <ul>
        <li>Go to <a href="{% url 'basic_app:create' %}">Add/Remove Player</a> page </li>
        <li>Enter details, leaving date as default (now)</li>
      </ul>

      <br>

      <li>To remove a player from Taxi or IR squad:</li>
        <ul>
          <li>Find the player on this page and press on their name</li>
          <li>Update Changed in/out to "out"</li>
        </ul>

      <br>

      <li><em>Note:</em> If you are re-adding a player, use a new entry so it can be checked whether the 4 week criteria has been met</li>
      <li> Only use the delete option for errors</li>
  </ul>
</div>

  {% if schools %}
  <div class="container">
    <table class="table-striped">
      <thead>
        <th style="width:12%">Team</th>
        <th style="width:12%">Player</th>
        <th style="width:12%">Date of transaction</th>
        <th style="width:12%">Roster</th>
        <th style="width:12%">Current Status</th>
      </thead>

      {% for school in schools %}
        <tr>
          <td>{{ school.team }} </td>
          <td><a href="{{school.id}}/">{{ school.player }}</a></td>
          <td>{{ school.added_time }}</td>
          <td>{{ school.roster }}</td>
          <td>{{ school.change }}</td>
        </tr>
      {% endfor %}
  </table>
  </div>


  {% else %}
    <p>No Records. Table Not Created.</p>
  {% endif %}

{% endblock %}

AdvCBV/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Transactions</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:create' %}">Add/Remove Player</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:rosters' %}">Rosters</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>
</html>

AdvCBV/templates/index.html
{% extends "base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Home</h1>

    <p>Easy enough way to keep track of everything</p>
  </div>
{% endblock %}